FROM node:20-alpine3.16

WORKDIR /app

COPY package.json .
COPY tsconfig.json .
COPY ecosystem.config.js .
COPY .env.development .
COPY ./src ./src
COPY ./swagger ./swagger

RUN apk add python3
RUN npm install pm2 -g
RUN npm install
RUN npm rn build

EXPOSE 3000

CMD ["pm2-runtime", "start", "ecosystem.config.js","--env", "development"]